name: Update Changelog on Main Push

on:
  push:
    branches: [main]

jobs:
  changelog:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to commit back to repo

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure full history

    - name: Fetch all branches
      run: git fetch --all

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      run: pip install -r requirements.txt || true

    - name: Generate Unreleased changelog
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        python scripts/changelog/main.py unreleased

    - name: Commit changelog if changed
      run: |
        if git diff --quiet CHANGELOG.md; then
          echo "No changes to commit"
        else
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md"
          git push
        fi
