name: Update Changelog in PR

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  changelog:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # allows committing back to repo

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # full history

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      run: pip install -r requirements.txt || true

    - name: Generate Unreleased changelog
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        python scripts/changelog/main.py unreleased

    - name: Commit changelog if changed
      run: |
        if git diff --quiet CHANGELOG.md; then
          echo "No changes to commit"
        else
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md"
          git push
        fi
